<a href="https://colab.research.google.com/github/Sriram-764/Data-Warehousing-and-Data-Mining/blob/main/DWDM_Experiment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# importing the require modules

import numpy as np
import pandas as pd

In [ ]:
# Loading the dataset

data = pd.read_csv('collegePlace.csv')

data.head()

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   
4   22    Male                     Mechanical            0     8       1   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1  
4                  0            1

**Transform the data into labels**

In [4]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

data['Gender'] = encoder.fit_transform(data['Gender'])

data['Stream'] = encoder.fit_transform(data['Stream'])

# ***Similarity and Dissimilarity measures***

**cosine similarity**

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim = cosine_similarity(data.drop(columns = ['Hostel', 'Gender']))

print("Cosine similarity matrix: ")
print(cos_sim)

Cosine similarity matrix: 
[[1.         0.99536924 0.99473521 ... 0.99643683 0.99386637 0.99003118]
 [0.99536924 1.         0.98833275 ... 0.98901397 0.99694135 0.99787715]
 [0.99473521 0.98833275 1.         ... 0.99822248 0.98975224 0.98176744]
 ...
 [0.99643683 0.98901397 0.99822248 ... 1.         0.99179985 0.983245  ]
 [0.99386637 0.99694135 0.98975224 ... 0.99179985 1.         0.99693353]
 [0.99003118 0.99787715 0.98176744 ... 0.983245   0.99693353 1.        ]]


**Euclidean Distance**

In [10]:
from sklearn.metrics.pairwise import euclidean_distances

euclid_distance = euclidean_distances(data.drop(columns = ['Hostel', 'Gender']))

print("Euclidian distance matrix: ")
print(euclid_distance)

Euclidian distance matrix: 
[[0.         2.64575131 2.44948974 ... 2.         2.64575131 3.46410162]
 [2.64575131 0.         3.60555128 ... 3.60555128 2.         2.64575131]
 [2.44948974 3.60555128 0.         ... 1.41421356 3.31662479 4.69041576]
 ...
 [2.         3.60555128 1.41421356 ... 0.         3.         4.47213595]
 [2.64575131 2.         3.31662479 ... 3.         0.         2.23606798]
 [3.46410162 2.64575131 4.69041576 ... 4.47213595 2.23606798 0.        ]]


**Pearson's correlation**

In [24]:
from scipy.stats import pearsonr

# Finding the correlation of the dataset
corr, _ = pearsonr(data['CGPA'], data['PlacedOrNot'])

print("Correlation coffecient = ", corr)

Correlation coffecient =  0.5886480477350889


**Jaccard similarity**

In [31]:
from sklearn.metrics import jaccard_score

jaccard_sim = jaccard_score(data['HistoryOfBacklogs'], data['PlacedOrNot'])

print(jaccard_sim)

0.15836392239119035


**Manhattan distance**

In [32]:
from sklearn.metrics.pairwise import manhattan_distances

man_dis = manhattan_distances(data)

print(man_dis)

[[0. 6. 6. ... 5. 6. 7.]
 [6. 0. 8. ... 9. 6. 7.]
 [6. 8. 0. ... 3. 6. 9.]
 ...
 [5. 9. 3. ... 0. 3. 8.]
 [6. 6. 6. ... 3. 0. 5.]
 [7. 7. 9. ... 8. 5. 0.]]
